FROM openjdk:17

COPY AdvancedInternshipManagementSystem /app/AdvancedInternshipManagementSystem
WORKDIR /app

RUN javac AdvancedInternshipManagementSystem/*.java
CMD ["java", "AdvancedInternshipManagementSystem.Main"]